In [ ]:
import numpy as np
import matplotlib.pyplot as plt
  

# STUDENT ID NUMBER: 

# INSTRUCTIONS

1. Put your student ID number (no other identifying features).  
If collaborating, put collaborators' id numbers underneath (again, no identifying features).
1. Submit both a notebook and exported PDF of the notebook after restart-and-run-all.  
    1. Submitted notebook must run in reasonable time.
    1. Ensure the exported pdf is LaTex formatted. 
1. No formal written section, but some of the combinatorial search questions may be abbreviated by specific algorithm choices.  
Justify algorithm choices outside of brute-force search in a separate typset pdf. 
1. For the coding section:
    1. Limit code answers to the designated spaces in functions (marked off by "###") and cells (marked by "### DO: *\<instructions\>*").  
       You may add extra cells to run subroutines (in order), but only marked cells will be graded. 
    1. Do not change the provided cells, or their order.  
       Any detected alterations will zero out that section. 
       
### Tips
- You are encouraged to work either alone or with your official partner, but not more.  
- For the coding section, test and sanity-check your work extensively.  

# Coding [$4\times 25 = 100$ pts]

## Ex. 1 - N-queens

Make a function to generate all valid arrangements of $N$-queens on an $N\times N$ chess board s.t. no queens attack each other.  
Ensure your results are valid up to $N = 8$.  
Check against a known table. 

Bonus 10 points to the highest $N$ in the class that runs in under a minute (as run on my system, ties split the points).  

In [2]:
### DO: Make a function to read a text file containing arrangements of N-queens on a board to ensure no queens attack each other.  
### Prove it works. 




In [3]:
### DO: Make a function to write a (new) text file containing arrangements of N-queens on a board s.t. no queens attack each other. 
### Use your first function to test this one. Do not use this to prove the first one works. 
### Name your files s.t. it declares the value of N in the name. 




In [4]:
### DO: Check your counts agree vs. known counts.


## Ex. 2 - Qubic

*Tic-tac-toe* is a game played on a $3\times 3$ grid, where player 1 plays X's and player 2 plays O's.   
Players take turn putting X's and O's in the grid.  
The winner is the first player to make 3-in-a-row either horizontally, vertically, or diagonally.  

*Qubic* is tic-tac-toe played in 3-dimensions, where the winning line may also go across the depth of the grid.  
When it was produced, it was played on a $4 \times 4 \times 4$ grid.  
For simplicity, consider only the $3 \times 3 \times 3$ variant.  



In [5]:
### DO: Write a function to list all the valid games of tic-tac-toe in a separate text file




In [6]:
### DO: Write a function to list all the valid games of qubic in a separate text file




In [7]:
### DO: Determine if there is a known winner for both tic-tac-toe and qubic, assuming perfect play.




## Ex. 3 - Queen Coloring 

The set of legal queen moves per square on a chess board defines a graph known as the queen's graph.  
The smallest number of colours needed to make a proper coloring of this graph for an $8\times 8$ board is known to be $9$.  

In [8]:
### DO: Make a function to find a valid 9-coloring of the queen's graph on an 8x8 board. 




In [9]:
### DO: Prove the colouring is proper, and the graph is a queen's graph. 




## Ex. 4 - Knight's Tour

The set of legal knight moves per square on a chess board defines a graph known as the knight's graph.  
A tour is a sequence of edges/vertices that, if traversed, visits each vertex exactly once (i.e. without doubling back).  


In [10]:
### DO: Make a function to find a sequence of knight moves on an $8\times 8$ chess board s.t. all squares are visited only once.  
### Let it start from any square on the board.  
### The tour may be open or closed (i.e. it does not need to loop back to itself as in TSP). 

def initboard(size):
    board = np.full((size, size), 0, dtype=int)
    return board

def knights_tour(y, x, board, moves):
    size = len(board)
    knight = [(1, 2), (2, 1), (-1, 2), (-2, 1), (1, -2), (2, -1), (-2, -1), (-1, -2)]
    def valid_check(y, x, board):
        if 0 <= x < size and 0 <= y < size and board[y][x] == 0:
            return True
        else:
            return False
    def count_moves(y, x, board):
        count = 0
        for i, j in knight:
            ny, nx = y+i, x+j
            if valid_check(ny, nx, board):
                count += 1
        return count
    board[y][x] = moves
    if moves == size ** 2:
        return True
    next_move = []
    for i, j in knight:
        ny, nx = y + i, x + j
        if valid_check(ny, nx, board):
            move_forward = count_moves(ny, nx, board)
            next_move.append(((ny, nx), move_forward))
    next_move.sort(key=lambda x:x[1])
    for (ny,nx), _ in next_move:
        if knights_tour(ny, nx, board, moves+1):
            return True
        board[ny][nx]=0
    return False

In [18]:
# DO: Prove that your method visits all squares exactly once

for i in range(20):
    board = initboard(8)
    start_x, start_y = np.random.randint(0, 8), np.random.randint(0, 8)
    print("Starting x and y:", start_x+1, "&", start_y+1) # so coordinates go from 1-8 instead of 0-7
    if knights_tour(start_y, start_x, board, 1):
        print("Knight's Tour found:")
        print(board)
        print("Is there exactly one instance of each number 1-64?", np.array_equal(np.sort(board.flatten()), np.arange(1, 65)))
        print("8*8=64, is there any number higher than 64 present?", np.any(board>64))
    else:
        print("No tour found.")

Starting x and y: 6 & 7
Knight's Tour found:
[[ 8 39 10 51  6 37 20 35]
 [11 52  7 38 21 34  5 30]
 [40  9 54 33 50 31 36 19]
 [53 12 41 62 47 22 29  4]
 [42 61 46 55 32 49 18 23]
 [13 58 63 48 45 26  3 28]
 [64 43 60 15 56  1 24 17]
 [59 14 57 44 25 16 27  2]]
Is there exactly one instance of each number 1-64? True
8*8=64, is there any number higher than 64 present? False
Starting x and y: 8 & 7
Knight's Tour found:
[[48 13 50 41 46 15 62 59]
 [39 26 47 14 61 58 45 16]
 [12 49 40 51 42 63 60 55]
 [25 38 27 64 57 54 17 44]
 [28 11 52 37 18 43 56 35]
 [21 24 29 32 53 36  3  6]
 [10 31 22 19  8  5 34  1]
 [23 20  9 30 33  2  7  4]]
Is there exactly one instance of each number 1-64? True
8*8=64, is there any number higher than 64 present? False
Starting x and y: 5 & 5
Knight's Tour found:
[[15 54 29 52 17 38 27 24]
 [30 51 16 39 28 25 18 37]
 [55 14 53 32 35 40 23 26]
 [60 31 50 41 46 33 36 19]
 [13 56 61 34  1 20 45 22]
 [64 59 10 49 42 47  2  5]
 [ 9 12 57 62  7  4 21 44]
 [58 63  8 11 