In [ ]:
import numpy as np
import sys
import time
import matplotlib.pyplot as plt
import itertools
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# STUDENT ID NUMBER: 

# INSTRUCTIONS

1. Put your student ID number (no other identifying features).  
If collaborating, put collaborators' id numbers underneath (again, no identifying features).
1. Submit both a notebook and exported PDF of the notebook after restart-and-run-all.  
    1. Submitted notebook must run in reasonable time.
    1. Ensure the exported pdf is LaTex formatted. 
1. No formal written section, but some of the combinatorial search questions may be abbreviated by specific algorithm choices.  
Justify algorithm choices outside of brute-force search in a separate typset pdf. 
1. For the coding section:
    1. Limit code answers to the designated spaces in functions (marked off by "###") and cells (marked by "### DO: *\<instructions\>*").  
       You may add extra cells to run subroutines (in order), but only marked cells will be graded. 
    1. Do not change the provided cells, or their order.  
       Any detected alterations will zero out that section. 
       
### Tips
- You are encouraged to work either alone or with your official partner, but not more.  
- For the coding section, test and sanity-check your work extensively.  

# Coding [$4\times 25 = 100$ pts]

## Ex. 1 - N-queens

Make a function to generate all valid arrangements of $N$-queens on an $N\times N$ chess board s.t. no queens attack each other.  
Ensure your results are valid up to $N = 8$.  
Check against a known table. 

Bonus 10 points to the highest $N$ in the class that runs in under a minute (as run on my system, ties split the points).  

In [ ]:
### DO: Make a function to read a text file containing arrangements of N-queens on a board to ensure no queens attack each other.  
### Prove it works. 

def safe(row,col,l,n):

    trow=row
    tcol=col
    while row>=0 and col>=0:
        if l[row][col]=="Q":
            return False
        row-=1
        col-=1
    row=trow
    col=tcol
    while col>=0:
        if l[row][col]=="Q":
            return False
        col-=1
    col=tcol
    while row<n and col>=0:
        if l[row][col]=="Q":
            return False
        row+=1
        col-=1
    return True

def is_valid_board_configuration(board: list, n: int):
    queens_positions = []
    for r in range(n):
        for c in range(n):
            if board[r][c] == 'Q':
                queens_positions.append((r, c))

    # Check for conflicts between all pairs of queens
    num_queens = len(queens_positions)
    for i in range(num_queens):
        r1, c1 = queens_positions[i]
        for j in range(i + 1, num_queens):
            r2, c2 = queens_positions[j]

            # Check same row
            if r1 == r2:
                return False
            # Check same column
            if c1 == c2:
                return False
            # Check same diagonal
            if abs(r1 - r2) == abs(c1 - c2):
                return False
    return True

def read_and_validate_n_queens_solutions(filename: str, n: int):
    print(f"\n Validating Solutions from '{filename}' for N = {n}")
    with open(filename, 'r') as f:
        lines = f.readlines()

    current_board_lines = []
    solution_count = 0
    valid_solutions = 0

    # Helper function to process the accumulated board lines
    def process_current_board():
        nonlocal solution_count, current_board_lines, valid_solutions
        if current_board_lines: # Only process if there are lines accumulated
            solution_count += 1
            # Filter out any potential empty strings that might have snuck in (though strip() should handle most)
            board = [row for row in current_board_lines if row]
            
            # Validate board dimensions
            if len(board) != n or any(len(row) != n for row in board):
                print(f"Solution {solution_count}: Invalid board dimensions. Expected {n}x{n}, got {len(board)}x{len(board[0]) if board else 0}.")
            else:
                is_valid = is_valid_board_configuration(board, n)
                if is_valid:
                    print(f"Solution {solution_count}: VALID")
                    valid_solutions +=1
                if not is_valid:
                    print(f"Solution {solution_count}: INVALID")
                    print("-" * 10)
                    for row_str in board:
                        print(row_str)
                    print("-" * 10)
            current_board_lines = [] # Reset for next board

    for line in lines:
        line = line.strip()

        # If it's an empty line, or a known header/separator, process the accumulated board
        # This handles both the generated file format and user-provided format with empty line separators
        if not line or \
            line.startswith("N-Queens Solutions for N =") or \
            line.startswith("Total Solutions:") or \
            line.startswith("Solution ") or \
            line.startswith("="*20):
            process_current_board()
            continue # Move to the next line after processing/skipping

        # If it's a board row, add it to current_board_lines
        # Ensure it's a valid board row (only '.' or 'Q' and correct length)
        if all(char in ('.', 'Q') for char in line) and len(line) == n:
            current_board_lines.append(line)
        else:
            # Warn about unexpected lines that don't fit the board row pattern
            print(f"Warning: Skipping unexpected line in file: '{line}' (Length: {len(line)}, Expected N: {n})")
    process_current_board()
    
N = 8
txt_file_name = "NQueens_filereader_test.txt"

read_and_validate_n_queens_solutions(txt_file_name, N)




 Validating Solutions from 'NQueens_filereader_test.txt' for N = 8
Solution 1: VALID
Solution 2: VALID
Solution 3: VALID
Solution 4: INVALID
----------
Q.......
Q.......
Q.......
Q.......
Q.......
Q.......
Q.......
Q.......
----------
Solution 5: VALID
4


Proof was done by creating a txt file with all possible configurations of placing N queens   
with the condition of having one queen per row since this is a requirement for the N queens problem.

In [102]:
#Modified version of file reader to only return amount of valid and invalid solutions
def modified_read_and_validate_n_queens_solutions(filename: str, n: int):
    print(f"\n Validating Solutions from '{filename}' for N = {n}")
    with open(filename, 'r') as f:
        lines = f.readlines()

    current_board_lines = []
    solution_count = 0
    valid_solutions = 0
    invalid_solutions = 0

    # Helper function to process the accumulated board lines
    def process_current_board():
        nonlocal solution_count, current_board_lines, valid_solutions, invalid_solutions
        if current_board_lines: # Only process if there are lines accumulated
            solution_count += 1
            # Filter out any potential empty strings that might have snuck in (though strip() should handle most)
            board = [row for row in current_board_lines if row]
            
            # Validate board dimensions
            if len(board) != n or any(len(row) != n for row in board):
                print(f"Solution {solution_count}: Invalid board dimensions. Expected {n}x{n}, got {len(board)}x{len(board[0]) if board else 0}.")
            else:
                is_valid = is_valid_board_configuration(board, n)
                if is_valid:
                    valid_solutions +=1
                if not is_valid:
                    invalid_solutions +=1
            current_board_lines = [] # Reset for next board

    for line in lines:
        line = line.strip()

        # If it's an empty line, or a known header/separator, process the accumulated board
        # This handles both the generated file format and user-provided format with empty line separators
        if not line or \
            line.startswith("N-Queens Solutions for N =") or \
            line.startswith("Total Solutions:") or \
            line.startswith("Solution ") or \
            line.startswith("="*20):
            process_current_board()
            continue # Move to the next line after processing/skipping

        # If it's a board row, add it to current_board_lines
        # Ensure it's a valid board row (only '.' or 'Q' and correct length)
        if all(char in ('.', 'Q') for char in line) and len(line) == n:
            current_board_lines.append(line)
        else:
            # Warn about unexpected lines that don't fit the board row pattern
            print(f"Warning: Skipping unexpected line in file: '{line}' (Length: {len(line)}, Expected N: {n})")
    process_current_board()

    print(f"Validation Summary for '{filename}':")
    print(f"Total Valid Solutions: {valid_solutions}")
    print(f"Total Invalid Solutions: {invalid_solutions}")
    
def all_configurations_one_queen_per_row(N):

    n_value = N
    all_placements = []
    # Generate all permutations of column indices for each row
    # Each permutation represents a unique placement of 8 queens (one per row, one per column)
    for p in itertools.permutations(range(n_value)):
        board = ['.' * n_value for _ in range(n_value)]
        for row_idx, col_idx in enumerate(p):
            board[row_idx] = board[row_idx][:col_idx] + 'Q' + board[row_idx][col_idx+1:]
        all_placements.append(board)
    
    print(f"\nGenerating and Saving all {len(all_placements)} possible {n_value}-Queens placements (one per row/column)")

    filename = f"AllSolutions_8Queens.txt"
    with open(filename, 'w') as f:
            for i, board in enumerate(all_placements):
                for row_str in board:
                    f.write(row_str + "\n")
                f.write("\n")
    print(f"Successfully wrote {len(all_placements)} solutions to '{filename}'")
    print(f"Finished generating and saving all {n_value}-Queens placements.")

    return filename

one_queen_per_row_txt_file = all_configurations_one_queen_per_row(N)
modified_read_and_validate_n_queens_solutions(one_queen_per_row_txt_file, 8)


Generating and Saving all 40320 possible 8-Queens placements (one per row/column)
Successfully wrote 40320 solutions to 'AllSolutions_8Queens.txt'
Finished generating and saving all 8-Queens placements.

 Validating Solutions from 'AllSolutions_8Queens.txt' for N = 8
Validation Summary for 'AllSolutions_8Queens.txt':
Total Valid Solutions: 92
Total Invalid Solutions: 40228


In [104]:
### DO: Make a function to write a (new) text file containing arrangements of N-queens on a board s.t. no queens attack each other. 
### Use your first function to test this one. Do not use this to prove the first one works. 
### Name your files s.t. it declares the value of N in the name. 

def safe(row,col,l,n):

    trow=row
    tcol=col
    while row>=0 and col>=0:
        if l[row][col]=="Q":
            return False
        row-=1
        col-=1
    row=trow
    col=tcol
    while col>=0:
        if l[row][col]=="Q":
            return False
        col-=1
    col=tcol
    while row<n and col>=0:
        if l[row][col]=="Q":
            return False
        row+=1
        col-=1
    return True

def solve(col,m,l,n):
    if col==n:
        m.append(l[:])
        return
    for row in range(n):
        if safe(row,col,l,n):
            l[row]=l[row][:col]+"Q"+l[row][col+1:]
            solve(col+1,m,l,n)
            l[row]=l[row][:col]+"."+l[row][col+1:]

def solveNQueens(n: int):
    m=[]
    l=['.'*n for _ in range(n)]
    solve(0,m,l,n)
    print(len(m))
    return m

def write_n_queens_to_file(n: int, solutions: list):
    filename = f"NQueens_solutions_{n}.txt"
    try:
        with open(filename, 'w') as f:
            if not solutions:
                f.write("No solutions found.\n")
            else:
                for i, board in enumerate(solutions):
                    for row_str in board:
                        f.write(row_str + "\n")
                    f.write("\n")
        print(f"Successfully wrote {len(solutions)} solutions to '{filename}'")
    except IOError as e:
        print(f"Error writing to file '{filename}': {e}")
    
    return filename

queens_solutions = solveNQueens(N)
N_QUEENS_TXT_FILE = write_n_queens_to_file(N, queens_solutions)

modified_read_and_validate_n_queens_solutions(N_QUEENS_TXT_FILE, 8)



92
Successfully wrote 92 solutions to 'NQueens_solutions_8.txt'

 Validating Solutions from 'NQueens_solutions_8.txt' for N = 8
Validation Summary for 'NQueens_solutions_8.txt':
Total Valid Solutions: 92
Total Invalid Solutions: 0


In [103]:
### DO: Check your counts agree vs. known counts.
def count_n_queens_solutions(n):
    def solve(row, cols, diag1, diag2):
        nonlocal count
        if row == n:
            count += 1
            return
        bits = ~(cols | diag1 | diag2) & ((1 << n) - 1)
        while bits:
            p = bits & -bits
            bits ^= p
            solve(row + 1, cols | p, (diag1 | p) << 1, (diag2 | p) >> 1)

    count = 0
    solve(0, 0, 0, 0)
    return count

# Known correct number of solutions for N = 1 to 10
known_counts = {
    1: 1,
    2: 0,
    3: 0,
    4: 2,
    5: 10,
    6: 4,
    7: 40,
    8: 92,
    9: 352,
    10: 724
}

print(f"{'N':>2} | {'Found':>6} | {'Expected':>8} | {'Match'}")
print("-" * 33)

for n in range(1, 11):
    found = count_n_queens_solutions(n)
    expected = known_counts[n]
    match = "Yes" if found == expected else "No"
    print(f"{n:>2} | {found:>6} | {expected:>8} | {match}")

 N |  Found | Expected | Match
---------------------------------
 1 |      1 |        1 | Yes
 2 |      0 |        0 | Yes
 3 |      0 |        0 | Yes
 4 |      2 |        2 | Yes
 5 |     10 |       10 | Yes
 6 |      4 |        4 | Yes
 7 |     40 |       40 | Yes
 8 |     92 |       92 | Yes
 9 |    352 |      352 | Yes
10 |    724 |      724 | Yes


## Ex. 2 - Qubic

*Tic-tac-toe* is a game played on a $3\times 3$ grid, where player 1 plays X's and player 2 plays O's.   
Players take turn putting X's and O's in the grid.  
The winner is the first player to make 3-in-a-row either horizontally, vertically, or diagonally.  

*Qubic* is tic-tac-toe played in 3-dimensions, where the winning line may also go across the depth of the grid.  
When it was produced, it was played on a $4 \times 4 \times 4$ grid.  
For simplicity, consider only the $3 \times 3 \times 3$ variant.  



In [ ]:
### DO: Write a function to list all the valid games of tic-tac-toe in a separate text file
def check_win(board, player):
    for i in range(3):
        if all(board[i, :] == player):
            return True
            
    for j in range(3):
        if all(board[:, j] == player):
            return True
            
    if all(np.diag(board) == player) or all(np.diag(np.fliplr(board)) == player):
        return True
    
    return False

def is_game_over(board):
    return check_win(board, 1) or check_win(board, -1) or np.sum(np.abs(board)) == 9

def get_winner(board):
    if check_win(board, 1):
        return 1
    elif check_win(board, -1):
        return -1
    elif np.sum(np.abs(board)) == 9:
        return 0
    else:
        return None

def find_empty_positions(board):
    return [(i, j) for i in range(3) for j in range(3) if board[i, j] == 0]

def board_to_string(board):
    symbols = {0: '.', 1: 'X', -1: 'O'}
    lines = []
    for row in board:
        lines.append(''.join(symbols[cell] for cell in row))
    return '\n'.join(lines)

def game_to_string(game):
    """Convert a complete game (list of boards) to a readable string."""
    result = []
    for i, board in enumerate(game):
        result.append(f"Move {i}:")
        result.append(board_to_string(board))
        result.append("")
    
    winner = get_winner(game[-1])
    if winner == 1:
        result.append("Winner: X")
    elif winner == -1:
        result.append("Winner: O")
    else:
        result.append("Result: Draw")
    
    return '\n'.join(result)

def generate_all_games():
    """Generate all possible valid tic-tac-toe games."""
    games = []
    
    # Start with empty board
    initial_board = np.zeros((3, 3), dtype=int)
    
    # Use BFS to explore all possible games
    queue = deque([(initial_board, [initial_board], 1)])  # (current_board, game_history, current_player)
    
    # Progress tracking
    processed = 0
    print("Generating games...")
    
    # Use tqdm for progress bar
    with tqdm(desc="Processing game states", unit="states") as pbar:
        while queue:
            current_board, game_history, current_player = queue.popleft()
            processed += 1
            pbar.update(1)
            
            # Update description with current stats
            if processed % 1000 == 0:
                pbar.set_description(f"Processed {processed} states, {len(games)} complete games")
            
            # If game is over, add it to our list
            if is_game_over(current_board):
                games.append(game_history)
                continue
            
            # Try all possible moves for current player
            empty_positions = find_empty_positions(current_board)
            
            for i, j in empty_positions:
                # Make the move
                new_board = current_board.copy()
                new_board[i, j] = current_player
                
                # Add to game history
                new_game_history = game_history + [new_board]
                
                # Switch player and add to queue
                next_player = -current_player
                queue.append((new_board, new_game_history, next_player))
        
        pbar.set_description(f"Completed! Processed {processed} states, {len(games)} complete games")
    
    return games

def save_all_games_to_file(filename="all_tic_tac_toe_games.txt"):
    """Generate all valid tic-tac-toe games and save them to a text file."""
    print("Starting tic-tac-toe game generation...")
    games = generate_all_games()
    
    print(f"\nGenerated {len(games)} total games.")
    
    # Count outcomes
    print("Analyzing game outcomes...")
    x_wins = sum(1 for game in games if get_winner(game[-1]) == 1)
    o_wins = sum(1 for game in games if get_winner(game[-1]) == -1)
    draws = sum(1 for game in games if get_winner(game[-1]) == 0)
    
    print(f"X wins: {x_wins}")
    print(f"O wins: {o_wins}")
    print(f"Draws: {draws}")
    
    # Save to file with progress bar
    print(f"Saving games to {filename}...")
    with open(filename, 'w') as f:
        f.write("ALL VALID TIC-TAC-TOE GAMES\n")
        f.write("=" * 50 + "\n\n")
        f.write(f"Total games: {len(games)}\n")
        f.write(f"X wins: {x_wins}\n")
        f.write(f"O wins: {o_wins}\n")
        f.write(f"Draws: {draws}\n")
        f.write("\n" + "=" * 50 + "\n\n")
        
        # Use tqdm for file writing progress
        for i, game in enumerate(tqdm(games, desc="Writing games to file", unit="games"), 1):
            f.write(f"GAME {i}\n")
            f.write("-" * 20 + "\n")
            f.write(game_to_string(game))
            f.write("\n\n" + "=" * 50 + "\n\n")
    
    print(f"All games saved to {filename}")
    return games

if _name_ == "_main_":
    # Generate and save all games
    all_games = save_all_games_to_file()



In [ ]:
### DO: Write a function to list all the valid games of qubic in a separate text file
import numpy as np
from collections import deque
import time
import sys

def check_win_3d(board, player):
    """Check if a player has won on the 3x3x3 board."""
    # board is 3x3x3, check all possible winning lines
    
    # 1. Check rows in each plane (x-y planes for each z)
    for z in range(3):
        for y in range(3):
            if all(board[x, y, z] == player for x in range(3)):
                return True
        for x in range(3):
            if all(board[x, y, z] == player for y in range(3)):
                return True
    
    # 2. Check columns going through z-axis
    for x in range(3):
        for y in range(3):
            if all(board[x, y, z] == player for z in range(3)):
                return True
    
    # 3. Check diagonals in each x-y plane
    for z in range(3):
        # Main diagonal
        if all(board[i, i, z] == player for i in range(3)):
            return True
        # Anti-diagonal
        if all(board[i, 2-i, z] == player for i in range(3)):
            return True
    
    # 4. Check diagonals in each x-z plane
    for y in range(3):
        # Main diagonal
        if all(board[i, y, i] == player for i in range(3)):
            return True
        # Anti-diagonal
        if all(board[i, y, 2-i] == player for i in range(3)):
            return True
    
    # 5. Check diagonals in each y-z plane
    for x in range(3):
        # Main diagonal
        if all(board[x, i, i] == player for i in range(3)):
            return True
        # Anti-diagonal
        if all(board[x, i, 2-i] == player for i in range(3)):
            return True
    
    # 6. Check 3D diagonals (4 total)
    # Main 3D diagonal (0,0,0) to (2,2,2)
    if all(board[i, i, i] == player for i in range(3)):
        return True
    # (0,0,2) to (2,2,0)
    if all(board[i, i, 2-i] == player for i in range(3)):
        return True
    # (0,2,0) to (2,0,2)
    if all(board[i, 2-i, i] == player for i in range(3)):
        return True
    # (0,2,2) to (2,0,0)
    if all(board[i, 2-i, 2-i] == player for i in range(3)):
        return True
    
    return False

def is_game_over_3d(board):
    """Check if the 3D game is over (win or draw)."""
    return check_win_3d(board, 1) or check_win_3d(board, -1) or np.sum(np.abs(board)) == 27

def get_winner_3d(board):
    """Return the winner of the 3D game: 1 for X, -1 for O, 0 for draw, None if ongoing."""
    if check_win_3d(board, 1):
        return 1
    elif check_win_3d(board, -1):
        return -1
    elif np.sum(np.abs(board)) == 27:
        return 0
    else:
        return None

def find_empty_positions_3d(board):
    """Find all empty positions on the 3D board."""
    return [(i, j, k) for i in range(3) for j in range(3) for k in range(3) if board[i, j, k] == 0]

def board_to_string_3d(board):
    """Convert a 3D board state to a readable string."""
    symbols = {0: '.', 1: 'X', -1: 'O'}
    result = []
    
    for z in range(3):
        result.append(f"Level {z}:")
        for i in range(3):
            row = ''.join(symbols[board[i, j, z]] for j in range(3))
            result.append(f"  {row}")
        result.append("")
    
    return '\n'.join(result)

def game_to_string_3d(game):
    """Convert a complete 3D game (list of boards) to a readable string."""
    result = []
    for i, board in enumerate(game):
        result.append(f"Move {i}:")
        result.append(board_to_string_3d(board))
        result.append("")
    
    winner = get_winner_3d(game[-1])
    if winner == 1:
        result.append("Winner: X")
    elif winner == -1:
        result.append("Winner: O")
    else:
        result.append("Result: Draw")
    
    return '\n'.join(result)

def format_time(seconds):
    """Format time in seconds to a readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}m"
    elif seconds < 86400:
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        return f"{hours:.0f}h {minutes:.0f}m"
    else:
        days = seconds // 86400
        hours = (seconds % 86400) // 3600
        return f"{days:.0f}d {hours:.0f}h"

def create_progress_bar(progress, width=40):
    """Create a text-based progress bar."""
    filled = int(width * progress)
    bar = "█" * filled + "░" * (width - filled)
    return f"[{bar}] {progress:.1%}"

def print_progress_update(processed, games_count, queue_size, elapsed, avg_rate=None, estimated_remaining=None, queue_progress=None):
    """Print progress update that overwrites the previous content."""
    # Move cursor up to overwrite the previous 2 lines
    sys.stdout.write('\033[2A\r')
    
    if avg_rate and estimated_remaining is not None and queue_progress is not None:
        progress_bar = create_progress_bar(queue_progress)
        # First line: progress bar and main stats
        line1 = f"{progress_bar} | {processed:,} states | {games_count:,} games".ljust(80)
        # Second line: queue, rate, and timing
        line2 = f"Queue: {queue_size:,} | Rate: {avg_rate:.0f}/s | Elapsed: {format_time(elapsed)} | ETA: {format_time(estimated_remaining)}".ljust(80)
    else:
        line1 = f"Processed: {processed:,} states | Games: {games_count:,} | Queue: {queue_size:,}".ljust(80)
        line2 = f"Elapsed: {format_time(elapsed)} | Calculating processing rate...".ljust(80)
    
    # Write first line and move to next line
    sys.stdout.write(line1)
    sys.stdout.write('\033[1B\r')  # Move down 1 line, return to start
    # Write second line
    sys.stdout.write(line2)
    # Move cursor back up to first line
    sys.stdout.write('\033[1A\r')
    sys.stdout.flush()

def generate_all_games_3d():
    """Generate all possible valid 3D tic-tac-toe games."""
    games = []
    
    # Start with empty 3x3x3 board
    initial_board = np.zeros((3, 3, 3), dtype=int)
    
    # Use BFS to explore all possible games
    queue = deque([(initial_board, [initial_board], 1)])  # (current_board, game_history, current_player)
    
    # Progress tracking
    processed = 0
    last_update = 0
    update_interval = 1000
    start_time = time.time()
    
    # For estimation - we'll track processing rate
    rate_samples = []
    last_rate_check = start_time
    last_processed_count = 0
    
    print("Generating 3D tic-tac-toe games...")
    print("This will take significantly longer than 2D tic-tac-toe!")
    print("Progress estimation will improve as more data is processed...")
    print()
    
    # Reserve space for 2-line progress display
    print("")  # Line 1 for progress
    print("")  # Line 2 for timing
    
    # Initial progress display
    print_progress_update(0, 0, 1, 0.0)
    
    while queue:
        current_board, game_history, current_player = queue.popleft()
        processed += 1
        
        # Calculate processing rate every 5 seconds
        current_time = time.time()
        if current_time - last_rate_check >= 5.0:
            elapsed_for_sample = current_time - last_rate_check
            processed_in_sample = processed - last_processed_count
            current_rate = processed_in_sample / elapsed_for_sample
            
            rate_samples.append(current_rate)
            # Keep only last 10 samples for moving average
            if len(rate_samples) > 10:
                rate_samples.pop(0)
            
            last_rate_check = current_time
            last_processed_count = processed
        
        # Show progress updates
        if processed - last_update >= update_interval:
            queue_size = len(queue)
            elapsed = current_time - start_time
            
            # Calculate average rate and estimate completion
            if rate_samples and queue_size > 0:
                avg_rate = sum(rate_samples) / len(rate_samples)
                estimated_remaining_time = queue_size / avg_rate
                
                # Create progress visualization
                # Estimate progress based on queue size decay (very rough)
                max_queue_seen = getattr(generate_all_games_3d, 'max_queue', queue_size)
                if queue_size > max_queue_seen:
                    max_queue_seen = queue_size
                    generate_all_games_3d.max_queue = max_queue_seen
                
                # Progress estimation (this is approximate)
                if max_queue_seen > 0:
                    queue_progress = 1 - (queue_size / max_queue_seen)
                else:
                    queue_progress = 0
                
                print_progress_update(processed, len(games), queue_size, elapsed, 
                                    avg_rate, estimated_remaining_time, queue_progress)
            else:
                print_progress_update(processed, len(games), queue_size, elapsed)
            
            last_update = processed
            
            # Increase update interval as we go to avoid spam
            if processed > 10000:
                update_interval = 5000
            if processed > 50000:
                update_interval = 10000
            if processed > 100000:
                update_interval = 25000
        
        # If game is over, add it to our list
        if is_game_over_3d(current_board):
            games.append(game_history)
            continue
        
        # Try all possible moves for current player
        empty_positions = find_empty_positions_3d(current_board)
        
        for i, j, k in empty_positions:
            # Make the move
            new_board = current_board.copy()
            new_board[i, j, k] = current_player
            
            # Add to game history
            new_game_history = game_history + [new_board]
            
            # Switch player and add to queue
            next_player = -current_player
            queue.append((new_board, new_game_history, next_player))
    
    # Final update - move past progress area and show completion
    sys.stdout.write('\033[2B\r')  # Move down 2 lines past progress area
    final_time = time.time() - start_time
    print(f"Generation complete! Processed {processed:,} total states, found {len(games):,} complete games")
    print(f"Total time: {format_time(final_time)}")
    return gamesnt_progress_update(processed, games_count, queue_size, elapsed, avg_rate=None, estimated_remaining=None, queue_progress=None)
    """Print progress update that overwrites the previous content."""
    # Clear the current lines
    sys.stdout.write('\r' + ' ' * 100 + '\r')
    sys.stdout.write('\033[1A' + ' ' * 100 + '\r')  # Clear line above too
    
    if avg_rate and estimated_remaining is not None and queue_progress is not None:
        progress_bar = create_progress_bar(queue_progress)
        # First line: progress bar and main stats
        line1 = f"{progress_bar} | {processed:,} states | {games_count:,} games"
        # Second line: queue, rate, and timing
        line2 = f"Queue: {queue_size:,} | Rate: {avg_rate:.0f}/s | Elapsed: {format_time(elapsed)} | ETA: {format_time(estimated_remaining)}"
    else:
        line1 = f"Processed: {processed:,} states | Games: {games_count:,} | Queue: {queue_size:,}"
        line2 = f"Elapsed: {format_time(elapsed)} | Calculating processing rate..."
    
    # Write both lines
    sys.stdout.write(line1 + '\n' + line2)
    sys.stdout.write('\033[1A\r')  # Move cursor back to start of first line
    sys.stdout.flush()

def generate_all_games_3d():
    """Generate all possible valid 3D tic-tac-toe games."""
    games = []
    
    # Start with empty 3x3x3 board
    initial_board = np.zeros((3, 3, 3), dtype=int)
    
    # Use BFS to explore all possible games
    queue = deque([(initial_board, [initial_board], 1)])  # (current_board, game_history, current_player)
    
    # Progress tracking
    processed = 0
    last_update = 0
    update_interval = 1000
    start_time = time.time()
    
    # For estimation - we'll track processing rate
    rate_samples = []
    last_rate_check = start_time
    last_processed_count = 0
    
    print("Generating 3D tic-tac-toe games...")
    print("This will take significantly longer than 2D tic-tac-toe!")
    print("Progress estimation will improve as more data is processed...")
    print()
    
    # Initial progress display
    print_progress_update(0, 0, 1, 0.0)
    
    while queue:
        current_board, game_history, current_player = queue.popleft()
        processed += 1
        
        # Calculate processing rate every 5 seconds
        current_time = time.time()
        if current_time - last_rate_check >= 5.0:
            elapsed_for_sample = current_time - last_rate_check
            processed_in_sample = processed - last_processed_count
            current_rate = processed_in_sample / elapsed_for_sample
            
            rate_samples.append(current_rate)
            # Keep only last 10 samples for moving average
            if len(rate_samples) > 10:
                rate_samples.pop(0)
            
            last_rate_check = current_time
            last_processed_count = processed
        
        # Show progress updates
        if processed - last_update >= update_interval:
            queue_size = len(queue)
            elapsed = current_time - start_time
            
            # Calculate average rate and estimate completion
            if rate_samples and queue_size > 0:
                avg_rate = sum(rate_samples) / len(rate_samples)
                estimated_remaining_time = queue_size / avg_rate
                
                # Create progress visualization
                # Estimate progress based on queue size decay (very rough)
                max_queue_seen = getattr(generate_all_games_3d, 'max_queue', queue_size)
                if queue_size > max_queue_seen:
                    max_queue_seen = queue_size
                    generate_all_games_3d.max_queue = max_queue_seen
                
                # Progress estimation (this is approximate)
                if max_queue_seen > 0:
                    queue_progress = 1 - (queue_size / max_queue_seen)
                else:
                    queue_progress = 0
                
                print_progress_update(processed, len(games), queue_size, elapsed, 
                                    avg_rate, estimated_remaining_time, queue_progress)
            else:
                print_progress_update(processed, len(games), queue_size, elapsed)
            
            last_update = processed
            
            # Increase update interval as we go to avoid spam
            if processed > 10000:
                update_interval = 5000
            if processed > 50000:
                update_interval = 10000
            if processed > 100000:
                update_interval = 25000
        
        # If game is over, add it to our list
        if is_game_over_3d(current_board):
            games.append(game_history)
            continue
        
        # Try all possible moves for current player
        empty_positions = find_empty_positions_3d(current_board)
        
        for i, j, k in empty_positions:
            # Make the move
            new_board = current_board.copy()
            new_board[i, j, k] = current_player
            
            # Add to game history
            new_game_history = game_history + [new_board]
            
            # Switch player and add to queue
            next_player = -current_player
            queue.append((new_board, new_game_history, next_player))
    
    # Final update - clear progress line and show completion
    sys.stdout.write('\r' + ' ' * 100 + '\r')
    final_time = time.time() - start_time
    print(f"Generation complete! Processed {processed:,} total states, found {len(games):,} complete games")
    print(f"Total time: {format_time(final_time)}")
    return games

def save_all_games_3d_to_file(filename="all_3d_tic_tac_toe_games.txt", sample_size=None):    
    start_time = time.time()    
    games = generate_all_games_3d()    
    generation_time = time.time() - start_time
    print(f"\nGenerated {len(games):,} total games in {generation_time:.2f} seconds.")
    
    # Count outcomes
    x_wins = sum(1 for game in games if get_winner_3d(game[-1]) == 1)
    o_wins = sum(1 for game in games if get_winner_3d(game[-1]) == -1)
    draws = sum(1 for game in games if get_winner_3d(game[-1]) == 0)
    
    print(f"X wins: {x_wins:,}")
    print(f"O wins: {o_wins:,}")
    print(f"Draws: {draws:,}")
    
    games_to_save = games
    if sample_size and len(games) > sample_size:
        print(f"Saving only first {sample_size:,} games (out of {len(games):,} total)")
        games_to_save = games[:sample_size]
    
    # Save to file with progress updates
    print(f"\nSaving games to {filename}...")
    write_start = time.time()
    
    with open(filename, 'w') as f:
        f.write("ALL VALID 3D TIC-TAC-TOE GAMES (3x3x3)\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Total games generated: {len(games):,}\n")
        f.write(f"Games saved to file: {len(games_to_save):,}\n")
        f.write(f"X wins: {x_wins:,}\n")
        f.write(f"O wins: {o_wins:,}\n")
        f.write(f"Draws: {draws:,}\n")
        f.write(f"Generation time: {generation_time:.2f} seconds\n")
        f.write("\n" + "=" * 60 + "\n\n")
        
        # Write games with progress updates
        total_games = len(games_to_save)
        for i, game in enumerate(games_to_save, 1):
            if i % 1000 == 0 or i == total_games:
                elapsed = time.time() - write_start
                progress = i / total_games
                eta = elapsed / progress - elapsed if progress > 0 else 0
                print(f"Writing progress: {i:,}/{total_games:,} ({progress:.1%}) - "
                      f"Elapsed: {elapsed:.1f}s - ETA: {eta:.1f}s")
            
            f.write(f"GAME {i}\n")
            f.write("-" * 30 + "\n")
            f.write(game_to_string_3d(game))
            f.write("\n\n" + "=" * 60 + "\n\n")
    
    total_time = time.time() - start_time
    print(f"\nAll games saved to {filename}")
    print(f"Total time: {total_time:.2f} seconds")
    return games

def count_winning_lines_3d():
    count = 0
    count += 3 * 3 * 2  # 3 planes, 3 rows each, 2 directions (horizontal/vertical)
    count += 3 * 3  # 3x3 positions
    count += 3 * 2  # 3 planes, 2 diagonals each
    count += 3 * 2  # 3 planes, 2 diagonals each
    count += 3 * 2  # 3 planes, 2 diagonals each
    count += 4  # 4 space diagonals
    
    return count

if __name__ == "__main__":
    print(f"3D Tic-Tac-Toe has {count_winning_lines_3d()} possible winning lines")
    print("(compared to 8 in regular 2D tic-tac-toe)")
    print()
    
    # Generate games with a sample limit for demonstration
    # Remove sample_size=1000 to generate ALL games (warning: this could be huge!)
    all_games_3d = save_all_games_3d_to_file("all_3d_tic_tac_toe_games.txt", sample_size=None)



In [33]:
### DO: Determine if there is a known winner for both tic-tac-toe and qubic, assuming perfect play.




## Ex. 3 - Queen Coloring 

The set of legal queen moves per square on a chess board defines a graph known as the queen's graph.  
The smallest number of colours needed to make a proper coloring of this graph for an $8\times 8$ board is known to be $9$.  

In [105]:
### DO: Make a function to find a valid 9-coloring of the queen's graph on an 8x8 board. 
from collections import defaultdict

# Build Queen's Graph
def build_queens_graph():
    graph = defaultdict(set)
    for r1 in range(8):
        for c1 in range(8):
            for r2 in range(8):
                for c2 in range(8):
                    if (r1, c1) == (r2, c2):
                        continue
                    if r1 == r2 or c1 == c2 or abs(r1 - r2) == abs(c1 - c2):
                        graph[(r1, c1)].add((r2, c2))
    return graph

# Optimized graph coloring using degree heuristic + forward checking
def color_graph_optimized(graph, max_colors=9):
    # Sort nodes by descending degree (degree heuristic)
    board = sorted(graph.keys(), key=lambda x: -len(graph[x]))
    color_assignment = {}
    domains = {node: set(range(1, max_colors + 1)) for node in graph}

    def forward_check(node, color):
        removed = {}
        for neighbor in graph[node]:
            if neighbor not in color_assignment and color in domains[neighbor]:
                domains[neighbor].remove(color)
                removed.setdefault(neighbor, set()).add(color)
                if not domains[neighbor]:
                    # Domain wipeout
                    return False, removed
        return True, removed

    def restore_domains(removed):
        for node, colors in removed.items():
            domains[node].update(colors)

    def backtrack(index=0):
        if index == len(board):
            return True
        node = board[index]
        for color in sorted(domains[node]):  # try available colors
            if all(color_assignment.get(nei) != color for nei in graph[node]):
                color_assignment[node] = color
                valid, removed = forward_check(node, color)
                if valid and backtrack(index + 1):
                    return True
                restore_domains(removed)
                del color_assignment[node]
        return False

    if backtrack():
        return color_assignment
    else:
        return None

# Run optimized coloring
graph = build_queens_graph()
solution = color_graph_optimized(graph, max_colors=9)

# Prepare visualization
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def plot_colored_board(solution):
    fig, ax = plt.subplots(figsize=(8, 8))
    colors = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c']

    for row in range(8):
        for col in range(8):
            square_color = '#f0d9b5' if (row + col) % 2 == 0 else '#b58863'
            rect = patches.Rectangle((col, 7 - row), 1, 1, linewidth=1, edgecolor='black', facecolor=square_color)
            ax.add_patch(rect)

            assigned_color = solution.get((row, col))
            if assigned_color:
                ax.text(col + 0.5, 7 - row + 0.5, str(assigned_color),
                        ha='center', va='center', fontsize=16, fontweight='bold',
                        color=colors[assigned_color - 1])

    ax.set_xlim(0, 8)
    ax.set_ylim(0, 8)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_aspect('equal')
    plt.title("Optimized 9-Coloring of Queen's Graph", fontsize=14)
    plt.show()

if solution:
    plot_colored_board(solution)
else:
    print("No valid 9-coloring found.")


KeyboardInterrupt: 

In [ ]:
### DO: Prove the colouring is proper, and the graph is a queen's graph. 

def plot_colored_board(solution):
    fig, ax = plt.subplots(figsize=(8, 8))
    colors = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c']

    for row in range(8):
        for col in range(8):
            square_color = '#f0d9b5' if (row + col) % 2 == 0 else '#b58863'
            rect = patches.Rectangle((col, 7 - row), 1, 1, linewidth=1, edgecolor='black', facecolor=square_color)
            ax.add_patch(rect)

            assigned_color = solution.get((row, col))
            if assigned_color:
                ax.text(col + 0.5, 7 - row + 0.5, str(assigned_color),
                        ha='center', va='center', fontsize=16, fontweight='bold',
                        color=colors[assigned_color - 1])

    ax.set_xlim(0, 8)
    ax.set_ylim(0, 8)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_aspect('equal')
    plt.title("Optimized 9-Coloring of Queen's Graph", fontsize=14)
    plt.show()

if solution:
    plot_colored_board(solution)
else:
    print("No valid 9-coloring found.")


## Ex. 4 - Knight's Tour

The set of legal knight moves per square on a chess board defines a graph known as the knight's graph.  
A tour is a sequence of edges/vertices that, if traversed, visits each vertex exactly once (i.e. without doubling back).  


In [ ]:
### DO: Make a function to find a sequence of knight moves on an $8\times 8$ chess board s.t. all squares are visited only once.  
### Let it start from any square on the board.  
### The tour may be open or closed (i.e. it does not need to loop back to itself as in TSP). 

def initboard(size):
    board = np.full((size, size), 0, dtype=int)
    return board

def knights_tour(x, y, board, moves):
    size = len(board)
    knight = [(1, 2), (2, 1), (-1, 2), (-2, 1), (1, -2), (2, -1), (-2, -1), (-1, -2)]
    def valid_check(x, y, board):
        if 0 <= x < size and 0 <= y < size and board[x][y] == 0:
            return True
        else:
            return False
    def count_moves(x, y, board):
        count = 0
        for i, j in knight:
            nx, ny = x+i, y+j
            if valid_check(nx, ny, board):
                count += 1
        return count
    board[x][y] = moves
    if moves == size ** 2:
        return True
    next_move = []
    for i, j in knight:
        nx, ny = x + i, y + j
        if valid_check(nx, ny, board):
            move_forward = count_moves(nx, ny, board)
            next_move.append(((nx, ny), move_forward))
    next_move.sort(key=lambda x:x[1])
    for (nx,ny), _ in next_move:
        if knights_tour(nx, ny, board, moves+1):
            return True
        board[nx][ny]=0
    return False

In [49]:
# DO: Prove that your method visits all squares exactly once

Test_Cases_Knights = 20

for test in range(Test_Cases_Knights):
    board = initboard(8)
    start_x, start_y = np.random.randint(0, 8), np.random.randint(0, 8)
    print("Starting x and y:", start_y, "&", start_x)
    if knights_tour(start_x, start_y, board, 1):
        print("Knight's Tour found:")
        print(board, "\n")
    else:
        print("No tour found.")

Starting x and y: 3 & 4
Knight's Tour found:
[[12 59 14 39 10 37 24 33]
 [15 40 11 60 25 34  9 36]
 [58 13 64 41 38 43 32 23]
 [63 16 55 44 61 26 35  8]
 [54 57 62  1 42 31 22 27]
 [17 48 51 56 45 28  7  4]
 [50 53 46 19  2  5 30 21]
 [47 18 49 52 29 20  3  6]] 

Starting x and y: 4 & 2
Knight's Tour found:
[[51 14 57 44 53 16 21 42]
 [56 45 52 15 58 43  2 17]
 [13 50 63 54  1 20 41 22]
 [46 55 32 49 62 59 18  3]
 [33 12 47 64 19 40 23 60]
 [28 31 34 37 48 61  4  7]
 [11 36 29 26  9  6 39 24]
 [30 27 10 35 38 25  8  5]] 

Starting x and y: 6 & 2
Knight's Tour found:
[[29 26  7 62 21 24  5  2]
 [ 8 61 28 25  6  3 20 23]
 [27 30 63 42 59 22  1  4]
 [64  9 60 49 52 43 40 19]
 [31 54 51 58 41 48 15 44]
 [10 57 34 53 50 45 18 39]
 [35 32 55 12 37 16 47 14]
 [56 11 36 33 46 13 38 17]] 

Starting x and y: 1 & 3
Knight's Tour found:
[[23 32  3 64 25 30  5 40]
 [ 2 55 24 31  4 41 26 29]
 [33 22 61 44 63 28 39  6]
 [54  1 56 35 60 45 42 27]
 [21 34 53 62 43 36  7 38]
 [52 49 18 57 46 59 10 13]
 